service:
  name: lambda-example

plugins:
  - serverless-webpack
  - serverless-plugin-existing-s3
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

functions:
  home-list-a:
    handler: handler.homeList